### ISSUE TITLE
Procurement Concierge - Continued Implementation and Maintenance Support

### ISSUE THREAD

**Issue by bcdevex** [BCDevExchange/concierge#6]
<p>This issue has been auto-generated to facilitate questions about
<a href="https://bcdevexchange.org/opportunities/cwu/opp-procurement-concierge---continued-implementation-and-maintenance-support"> a paid opportunity</a> that has just been posted on the
<a href="https://bcdevexchange.org">BCDevExchange</a>.</p>

<p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-procurement-concierge---continued-implementation-and-maintenance-support">visit the opportunity page</a>.
The opportunity closes on <b>Wednesday, August 28th, 2019 at 16:00 PDT</b>.</p>

**Comment by ZachWoodward** [comment]
Hello Holly,
The product will be in a live/production ready state by the end of October. Additional maintenance is to be provided on a as when/needed basis without support from a PSB development team at this time.

Regards,
Zachary Woodward

**Comment by ZachWoodward** [comment]
Hello Jeremy,

The site does advise the winning proponent but we, at this time, do not actively post the winning submitted proposal.

Regards,
Zachary Woodward

**Comment by bcdevex** [comment]
This opportunity has been assigned
